# Generated by Django 4.2.10 on 2024-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="photos/%Y/%m/%d"),
        ),
    ]
