# Generated by Django 4.2.10 on 2024-02-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="photos/%Y/%m/%d"),
        ),
    ]
