# Generated by Django 4.2.10 on 2024-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_borrow_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="cover/%Y/%m/%d"),
        ),
    ]
