# Generated by Django 4.2.10 on 2024-02-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="borrowing_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
