# Generated by Django 4.2.10 on 2024-02-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_borrow_borrowing_date_alter_borrow_return_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="borrow", name="borrowing_date",),
    ]
